import type { Metadata } from "next";
import { inter, roboto_mono } from "../../style/fonts";
import { ThemeProvider } from "./providers";
import { Locale, i18n } from "../../../i18n.config";
import "../../style/globals.css";
import NavBar from './components/navbar/Navbar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang} className=' !scroll-smooth ' suppressHydrationWarning>
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
          <header className=" sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6 ">
            <NavBar lang={params.lang} />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
