import type { Metadata } from "next";
import { inter, roboto_mono } from "../style/fonts";
import "../style/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>{children}</body>
    </html>
  );
}
